name: Notica
description: watch later in notifications
full_description: 'A more complete description of the mobile app<br>
<br>With a lot of features:
<br>- Save what you need, fast
<br>- Be constantly reminded
<br>- Beautifully design
android: https://play.google.com/store/apps/details?id=com.aleksandar.notica

screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: https://telegra.ph/Replace-this-link-07-23

